### ISSUE TITLE
3.19.0 Build Error

### ISSUE THREAD

**Issue by thanoofayoob** [flutter/super_dash#198] opened 2024-02-27 07:27 UTC
### This is the error throwing### 
<img width="1063" alt="Screenshot 2024-02-27 at 12 53 39 PM" src="https://github.com/flutter/super_dash/assets/67316775/051dc664-e4b7-4d1f-9536-7d03a80150ab">
<img width="573" alt="Screenshot 2024-02-27 at 12 56 44 PM" src="https://github.com/flutter/super_dash/assets/67316775/3c17496d-6bc4-4e92-b8de-b5bef20b2afb">

**Comment by domesticmouse** [comment] 2024-02-28 02:48
Closing as duplicate of https://github.com/flutter/super_dash/issues/197

**Closed by domesticmouse** 2024-02-28 02:48 UTC
